//here is dealing with date
const now = new Date()
console.log(now.getFullYear())
const timestamp = now.getTime()
const myDate = new Date(timestamp)
console.log(myDate.getFullYear())
console.log(`Year :${now.getFullYear()}`)
console.log(`Month ${now.getMonth()}`)
console.log(`Day of Month ${now.getDate()}`)
console.log(`Hour: ${now.getHours()}`)
console.log(`Minute ${now.getMinutes()}`)
console.log(`Seconds ${now.getSeconds()}`)
console.log(`day : ${now.getDay()}`)
const dateOne = new Date('March 1 2017 12:00:00')
const dateTwo = new Date()
console.log(dateTwo.toString())
console.log(dateTwo.toTimeString())
console.log(dateTwo.toUTCString())
const dateOneTimestamp = dateOne.getTime()
const dateTwoTimestamp = dateTwo.getTime()
if(dateOneTimestamp<dateTwoTimestamp){
    console.log(dateOne.toString())
}else if(dateOneTimestamp>dateTwoTimestamp){
    console.log(dateTwo.toString())
}
